---

- name: TEST CUSTOM MODULE WORKS
  hosts: iosxe
  connection: local
  gather_facts: no

  tasks:

    - name: GATHER IOSXE CONFIGS
      iosxe_gather_configs:
        host: "{{ inventory_hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
        filter: version
      register: result

    - name: VIEW THE DATA STORED IN RESULT
      debug:
        var: result
