---

- name: TEST INTERFACE EXPANSION FILTER
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "{{ 'gi' | expand_interface_name }}"

    - debug:
        msg: "{{ 'loop' | expand_interface_name }}"

    - debug:
        msg: "{{ 'TUN' | expand_interface_name }}"

    - debug:
        msg: "{{ 'po100' | expand_interface_name }}"

    - debug:
        msg: "{{ 'virt' | expand_interface_name }}"


- name: TEST MULTIPLE INTERFACE EXPANSION FILTER
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "{{ 'gi' | expand_interface_names }}"

    - debug:
        msg: "{{ ['gig', 'port', 'mg' ] | expand_interface_names }}"

    - debug:
        msg: "{{ ['loop', 'virt', 'PRI0' ] | expand_interface_names }}"

    - debug:
        msg: "{{ 100 | expand_interface_names }}"
