global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'snmp'
    static_configs:
      - targets:
        - 'http-telegraf-01:9012'
        - 'dns-telegraf-01:9013'
