version: "3"
services:
  http-telegraf-01:
    image: telegraf:1.15
    container_name: http-telegraf-01
    volumes:
      - ./configs/http-telegraf-01.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - prometheus
    ports:
      - 9012:9012

  http-telegraf-02:
    image: telegraf:1.15
    container_name: http-telegraf-02
    volumes:
      - ./configs/http-telegraf-02.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - prometheus
    ports:
      - 9014:9014

  dns-telegraf-01:
    image: telegraf:1.15
    container_name: dns-telegraf-01
    volumes:
      - ./configs/dns-telegraf-01.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - prometheus
    ports:
      - 9013:9013

  prometheus:
    image: prom/prometheus:v2.21.0
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    tty: true

  grafana:
    image: grafana/grafana:7.2.1
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./configs/grafana-provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:

